### PR TITLE
ci: validate master after merge

### PR DESCRIPTION
**Pull request by RaananW**
> **Draft** — opened as draft at the coordinating session's request.

## Change-set shape — read this before reviewing

Stated plainly, because the proportion is not what the title implies and a reviewer should get to decide how to spend attention on it:

| Part | Lines | What it is |
| --- | --- | --- |
| `azure-pipelines.yml` + `TESTING.md` | ~372 | The thesis: a `master` trigger, six gated jobs, and the docs. Mostly the long WHY comments the house style asks for — the mechanism itself is **19 lines** of `trigger:`/`condition:`. |
| four files under `tests/lite/unit/` | 4,154 | Guards for that thesis, plus the `pipefail` fix below. |

So **92% of the diff is test code**, across 71 commits. That is a lot, and the honest account of how it got that way is that a long mutation-testing exchange with a sibling session kept finding true defects in the guards, and each fix was defensible on its own. Scope, though, is a property of the change set and not of the individual edit — every commit here passed the local test and the aggregate still drifted well past the brief.

Two consequences a reviewer may want to act on:

- **There are arguably two theses in here.** The `master` trigger is one. The `pipefail` fix — seven type-check steps that could not fail, described below — is a genuine bug found on the way, and `pipeline-piped-steps-set-pipefail.test.ts` (1,052 lines) guards *that*, not this. It is a clean candidate to split into its own PR if you would rather review the trigger on its own; it touches no file the trigger needs.
- **The guard files are far more thorough than the trigger strictly requires.** Nothing in them is speculative — every clause is pinned by a mutation that was measured to defeat it — but "each clause is justified" and "this volume belongs on this PR" are different claims, and only the first one is established.

No further hardening is going onto this PR. If something else turns up in these guards it becomes a follow-up.

## The gap

`azure-pipelines.yml` holds all nine validation jobs but was configured with `trigger: none` and only a `pr:` trigger. **Nothing validated `master` after a merge.** The only master-triggered pipelines are deploy/publish ones (`demos`, `playground`, `npm-publish*`) plus the daily `compat-sync` — so a build-level break would surface via a deploy, but no unit tests, lint, type-check, or compat validation ever ran on master.

Azure DevOps builds the PR *merge commit*, so a green PR only proves the branch was good against `master` **as it stood when the build ran**. Two PRs can each be green, both merge, and interact badly — a semantic conflict neither build could have seen (a renamed export plus a new caller of the old name; a tightened invariant plus new code that violates it). Nobody finds out until the *next* PR's build, which goes red for something it didn't do, and that author spends their afternoon bisecting someone else's merge. Worst case it survives to the weekly npm publish.

## What now runs on master

| Job                   | Duration | Why it qualifies                                                                                                               |
| --------------------- | -------- | ------------------------------------------------------------------------------------------------------------------------------ |
| **Unit Tests**        | ~10m37s  | Hermetic; also carries the package build (`--project build`)                                                                    |
| **Lint & Type Check** | ~2m27s   | Cheapest catch for a semantic conflict — a type error is exactly what a signature change + a new caller of the old one produces |
| **Compat Layer**      | ~2m26s   | Most exposed to semantic conflicts: a thin shim over the public surface, and the engine PR that breaks it has no reason to look |

They run in parallel, so the post-merge signal arrives in **~11 minutes**, dominated by Unit Tests.

**That ~11 minutes is agent time, not guaranteed wall time.** Every pipeline here uses Microsoft-hosted `ubuntu-latest`, so concurrency comes from an allocation shared across the whole `babylonjs` ADO organisation — including the main Babylon.js repo. When that pool is contended, jobs sit in `notStarted` before any of this runs. Observed while preparing this PR: on `cf2cbe95` both the bundle-manifest and playground builds stayed queued for 19+ minutes, where playground had completed within minutes on each of the five preceding master commits. So the number to plan against is ~11 minutes of *execution*, plus whatever the queue is at the time.

**Cost, stated plainly, since it is not free:** three jobs at 10m37s + 2m27s + 2m26s ≈ **15.5 agent-minutes per push to master**. For scale, one PR run of this same pipeline is ~150+ agent-minutes, dominated by Perf (53m), Bundle Size (42m) and Parity (37m) — so post-merge validation costs roughly a tenth of a single PR build. That is the right order of magnitude for catching semantic conflicts, and it is the number any future argument about trimming this should start from.

All three are hermetic — no cloud browser, no external service. That matters more than coverage here: a post-merge failure has no author to nudge and no PR to block, so it's only useful if red reliably means "master is broken" rather than "BrowserStack was busy".

## Bundle-ceiling enforcement on master — resolved

#526 has landed, so `azure-pipelines-bundle-manifest.yml` is now on `master`. It runs on every master push and executes `pnpm build:bundle-scenes`, which enforces the per-scene `maxRawKB` ceilings byte-exactly.

That makes the Bundle Size exclusion here verifiable rather than a promise: adding the 42-minute job to every merge would buy a second opinion on numbers the manifest pipeline already produces, and would roughly quadruple post-merge wall time.

One caveat, stated precisely, because I got this wrong on a first reading and the distinction matters:

**The manifest pipeline's CI trigger fired automatically for the first time on 2026-08-25 at 09:38:38 UTC**, on commit `cf2cbe95` (#612) — while this PR was open. Before that it had *no automatic history at all*: its ADO definition was created at 08:06:08 UTC that morning with exactly one build ever — `20260825.1`, `reason: manual`, started nine seconds later against `8ff3eb15`, and it **failed**. The four master pushes after #526 landed (#597, #601, #609, #613) triggered nothing, because the definition did not exist yet. So the earlier concern was never "queued and slow" — it was that the trigger was unexercised. It is now exercised, and it works.

The one manual run failed on an unresolved `$(STORAGE_ACCOUNT)` macro at the publish step — the upload template's *parameter* name, which no variable group exports (`playground` maps `$(TOOLS_STORAGE_ACCOUNT)`, `demos` hardcodes it). Empty account → HTTP 401. That is diagnosed and fixed in **#617**.

Verified independently here: `completed/failure` started `2026-08-25T08:06:17Z` on `8ff3eb15`, `<no run>` on the five preceding master commits.

**None of this blocks this PR, and the exclusion is on firmer ground than the word "failed" suggests.** The task timeline for that build is:

```
succeeded   28.0m  Build bundle scenes
failed       0.0m  Publish bundle-size baseline
```

`pnpm build:bundle-scenes` — the step that enforces the per-scene `maxRawKB` ceilings byte-exactly, which is the entire basis for excluding Bundle Size here — **ran green for 28 minutes against `8ff3eb15`, current master HEAD.** Every step before the publish succeeded. Only the upload failed, on the unresolved macro.

So the enforcement mechanism this PR's exclusion depends on has already been observed passing on real master content, and the trigger that invokes it has now been observed firing on a real master push. Both halves of the claim are evidenced. The one remaining gap is that the two have not yet been observed *in the same run*: the `cf2cbe95` run executes the pre-#617 YAML, so it is expected to build for ~28 minutes and then fail at the publish step on the unresolved `$(STORAGE_ACCOUNT)` — a diagnosed, fixed-in-#617 failure, not a ceiling violation. The first fully-green automatic run lands with #617.

This PR neither adds nor removes bundle coverage either way.

## ⚠️ This PR is blocked on #615 — and that is the point

`master` is **currently red**. A pristine `origin/master` fails `tsc -p tests/lite/tsconfig.json`:

```
tests/lite/unit/clustered-light.test.ts(287,13): error TS2353: Object literal may only specify known properties, and '_toneMappingHelpers' does not exist in type 'PbrComposerDeps'.
tests/lite/unit/pbr-lightmap.test.ts(262,13): error TS2353: ...
```

This was found while merging `master` into this branch. It is a semantic conflict between two individually-green PRs that merged 93 minutes apart — #597 removed `_toneMappingHelpers`/`_toneMappingCall` from `PbrComposerDeps`, and #601 added two call sites still passing them, having been validated before #597 landed. It has been broken since 2026-08-25.

It is fixed in **#615**, which should merge before this PR.

**Suggested sequence: #617 → #615 → this PR.** #617 (the bundle-manifest storage-account fix) is independent of the type breakage. Its original urgency was that the next master push would be the manifest pipeline's first-ever automatic run, so landing #617 first would let that run test both unknowns at once. That push has since happened (#612, `cf2cbe95`) without #617, so the trigger question is answered for free and the ~28-minute burn is already underway. #617 still goes first, for the narrower reason that it is the only thing standing between master and a green manifest run — but the sequence is no longer load-bearing for this PR.

This is an unplanned but fairly conclusive demonstration of the gap: a real break sat on `master` for weeks precisely because nothing type-checks `master` after a merge, and this PR's own Lint job now inherits it — the "innocent PR debugs someone else's regression" scenario, live. With this pipeline in place, #597 + #601 would have gone red on master within ~11 minutes of the second merge.

## Second finding: the type-check steps could not fail

While validating this branch I found that **seven type-check steps across the Lint and Compat jobs were incapable of failing** — a pre-existing bug, fixed here in `f915c65d`.

Each step pipes `tsc` through `sed` to convert TypeScript diagnostics into `##vso[task.logissue]` annotations:

```bash
npx tsc -p tests/lite/tsconfig.json --noEmit 2>&1 | sed -E 's/.../##vso[task.logissue ...]/'
```

A shell pipeline exits with the status of its **last** command. `sed` always succeeds, so `tsc`'s non-zero exit was discarded. And `task.logissue` only annotates — it does not fail a task. So the steps printed the errors and passed.

Demonstrated locally against master:

| invocation | exit |
| --- | --- |
| `tsc -p tests/lite/tsconfig.json --noEmit` | **2** |
| the same piped through `sed` (what CI ran) | **0** ← the bug |
| with `set -euo pipefail` | **2** |

This is why the #597/#601 breakage above survived weeks of green PR builds.

It matters directly for this PR: two of the three jobs now running on master are **Lint and Compat**. Without this fix, post-merge validation would have inherited the exact blind spot it exists to close and would have reported green on a broken master — arguably worse than no validation, because it would be trusted.

`set -euo pipefail` matches the convention already used in `azure-pipelines-bundle-manifest.yml`, `-compat-sync.yml` and `-npm-publish.yml`. Verified by extracting the step script straight from the YAML and executing it: exit 2 instead of 0, annotation output unchanged.

**And the invariant is now guarded, not just the instances.** Fixing seven steps by hand leaves nothing stopping an eighth arriving without the guard — and this defect is invisible when it recurs, because the symptom is a *green* job. `tests/lite/unit/pipeline-piped-steps-set-pipefail.test.ts` asserts that every inline pipeline script containing a pipe enables `pipefail`.

- **No exemption list needed.** Measured first: ten piped scripts repo-wide, all already compliant. A guard with a growing exception list is one that gets weakened, so it was worth checking the false-positive load before writing it.
- **Deliberately over-inclusive** — it flags piped scripts where a left-hand failure would be harmless, because adding `pipefail` unnecessarily costs nothing while missing one costs a disabled gate.
- **Three vacuity guards**, since a check that silently matches nothing is the same defect it exists to prevent: the file glob, the script-block reader, and the pipe detector each fail loudly rather than passing on an empty set.
- **All four failure paths exercised, not assumed.** Removing a real guard reports `azure-pipelines.yml:714`; breaking each collector fails with its own message. The first attempt at that negative test *passed* — it had mutated a prose mention of `set -euo pipefail` rather than a real one, which is precisely the trap being guarded against.

It lives in `tests/lite/unit/`, so it runs in the Unit Tests job — which this PR puts on master. The guard is enforced post-merge by the change it protects.

**Consequence:** this PR's own Lint job is now legitimately red, because the fix above makes it report the real master breakage. It goes green when #615 lands.

### The proof is a live A/B, not a local demonstration

The exit-code table above was produced by hand. There is a stronger demonstration available in CI right now, on two open PRs off the same master:

| PR | has the `pipefail` fix | `Lint & Type Check` |
| --- | --- | --- |
| **#530** (`f779fef2`) | no | **SUCCESS** |
| **#531** (this PR) | yes | **FAILURE** |

Both trees contain the *same two type errors*, and both inherit them from master rather than introducing them:

```
tests/lite/unit/clustered-light.test.ts:287   _toneMappingHelpers: ""
tests/lite/unit/pbr-lightmap.test.ts:262      _toneMappingHelpers: ""
packages/babylon-lite/src/pbr-composer.ts     PbrComposerDeps declares it 0 times
```

So #530 is not green because it is clean. It is green because the masking pipe is still in place. The difference between the two columns is one line, `set -euo pipefail`, and nothing else.

That is the argument for this PR in one table: **the evidence that the fix works is not a new test going green, it is a pre-existing failure finally being able to fail.** These two errors have been sitting in a passing build, and every PR built on master has been reporting a green type-check over them.

Worth stating plainly, because it bounds the blast radius: for as long as the pipe has been there, `Lint & Type Check` and `Compat Layer` have been reporting the *presence* of type errors as annotations while exiting 0. Any type error introduced in that window passed CI.

### A third case, from a sibling PR: a test file that passes and does not compile

PR #617 hit the same class of hole from the other side, and it is the sharpest example either of us has:

| signal | result |
| --- | --- |
| `vitest run` on the guard file | **2 passed** |
| `tsc -p tests/lite --noEmit` on the same file | **7 errors** (`noUncheckedIndexedAccess`) |

A test file that reports green while the type checker rejects it outright. It was found only because the two checkers were run *separately* — which is exactly what master does not do today and what this PR makes it do.

The reason to include it here is that it closes the most natural objection to the whole PR. "Surely the tests would have caught it" has somewhere to go when the unchecked thing is production code. It has nowhere to go when the unchecked thing is **the test itself**: a passing test is not evidence that the test compiles, and nothing in this repository was checking that on master.

Together the three cases describe one gap rather than three bugs:

- the seven piped steps — a check that ran, failed, and reported success;
- the two master type errors — a failure that existed for weeks with no build able to show it;
- #617's guard file — a file that satisfied one checker while another rejected it.

None of them is a test that was missing. All of them are a *check that was not run, or was run in a way that could not fail*. That is the thing this PR adds to master.

### The first reds after this lands are disclosures, not regressions

This PR changes what every *other* PR's type-check result means. That is worth stating
before it lands, because the failure mode is social rather than technical: an open PR that
is green today may go red the moment this merges, and the obvious explanation — "the CI
change broke it" — is wrong. The errors were always there; only the reporting was broken.

To bound that, master's actual type state was measured directly, running each of the six
`tsc -p` projects that `pnpm lint` invokes, individually, rather than through the masking
pipe:

| project | errors |
| --- | --- |
| `packages/babylon-lite` | 0 |
| `packages/babylon-lite-gl` | 0 |
| `lab` (`tsconfig.typecheck.json`) | 0 |
| `playground` | 0 |
| `tests/lite` | **2** — both #615's, listed above |
| `tests/gl` | 0 |

`eslint .` exits 0. **Master itself is hiding nothing beyond #615.** So this PR does not
uncover a backlog on master, and #615 is the whole of the blocking set.

The exposure is in the **12 currently-open PRs**, whose `Lint & Type Check` SUCCESS is
uninformative until this lands — a green check there presently means "the job ran", not
"the types are sound". One has already been confirmed by hand to carry five real errors
(`string | undefined` capture groups read as `string`) behind a green check, found only
because someone ran `tsc -p` directly.

Two consequences for whoever merges this:

- **Do not revert this PR to make a red go away.** A red appearing immediately after this
  lands is the job doing its job for the first time. The fix belongs in the PR that owns
  the error.
- **Landing order matters.** #615 must land first (see above). Beyond that, each open PR
  should be re-checked against its own `tsc -p` projects before merge rather than trusting
  a check that predates this change.

## Approach — master trigger on the existing file, PR-context jobs gated

Chosen over a separate `azure-pipelines-master-validation.yml`:

- **No drift.** The master jobs are literally the same job definitions the PR runs. A separate file — even with shared step templates — silently misses anything added to a PR job later (e.g. a new `tsc -p` project in Lint).
- **No manual ADO setup.** This pipeline is already registered and already authorized for its variable groups. A new YAML file requires creating the pipeline in the UI and re-authorizing variable groups before it runs even once.
- **Cost is six one-line conditions**, not a restructure. ADO renders the skipped jobs on master runs, which is self-documenting.

The gate:

```yaml
condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
```

`Build.SourceBranch` is `refs/pull/<n>/merge` on a PR build and `refs/heads/master` on a master push, so this skips a job exactly when the thing being built *is* master. Deliberately **not** `eq(Build.Reason, 'PullRequest')`, which would also skip these jobs on a manual queue against a feature branch — a real workflow (queueing a parity or perf run on demand) that this pipeline has always supported.

Note what that condition does **not** promise, because Copilot review caught me implying it did: *not master* is not *is a PR*. A build queued by hand against a feature branch is neither, and `System.PullRequest.*` is exactly as empty there as on master. So this is a master gate, not a PR-context guarantee. It is survivable only because every PR-context **step** already tolerates an absent PR — all four `GitHubComment@0` tasks are `continueOnError: true` and gated on a `POST_*_COMMENT` flag, and `validate:release-markers` falls back to commit-message scanning when `PR_NUMBER` is empty. Since that is now the stated *reason* for the weaker gate, it is asserted by `tests/lite/unit/pipeline-pr-comment-steps-guarded.test.ts` rather than left as prose. A job that genuinely cannot run without a PR should use `startsWith(variables['Build.SourceBranch'], 'refs/pull/')` instead.

The `succeeded()` half is not decoration: declaring any `condition:` on a job **replaces** the implicit default of `succeeded()`. I verified that no job in this file declares `dependsOn` (single stage, all nine parallel), so a bare `ne(...)` would behave identically today — but it would silently drop the failure guard the moment someone adds a `dependsOn` to a gated job. The compound form costs nothing and removes the trap.

The `GitHubComment@0` tasks carry the branch guard locally too, redundantly with their job condition, because a comment task with an empty `id` fails in a confusing way.

**No `paths:` filter on the master trigger, on purpose.** Master validation will run on doc-only commits; ~15.5 agent-minutes is accepted waste. A path filter is precisely the optimisation that later lets a real break through unvalidated — the filter has to encode which paths can affect a build, and that list is wrong the moment someone adds a config file, a script, a tsconfig `include`, or a generated-doc check that reads source (this repo has one: `pnpm gen:feature-doc:check` in the Lint job). The header comment says so, and points at `batch: true` as the correct lever if run count ever genuinely matters.

### The gating is now enforced, not just documented

A `condition:` is one line, carries no type, and was invisible to every other check here. I deleted all eight master gates and ran the full unit suite: **2052 passed**. The only mention of `refs/heads/master` anywhere under `tests/` was a sentence in a comment *describing* the gate. The property this whole PR rests on had no executable coverage.

`tests/lite/unit/pipeline-master-gating.test.ts` now fails in **both** directions:

- a job that reads PR context and lacks the gate — including context reached through a `- template:` it includes;
- a job in the post-merge set that **gains** a gate. That is the one worth reviewing: gating one more job never reads as a regression in a diff, and a master build that skips every job is *green* having validated nothing — the exact state this PR exists to end.

Writing it found a real hole in my own first draft. Matching markers against job bodies alone classified `PerfRegression` and `ParityCloud` as gated for cost only; both include `upload-test-report.yml`, which posts a `GitHubComment@0` keyed on `$(System.PullRequest.PullRequestNumber)`. Their gates are load-bearing for correctness too. Single-variable A/B with `ParityCloud` genuinely ungated — without template resolution: 4 passed, silent; with it: fires by name.

Subject is pipelines that build **both** a PR and master, which is exactly the hazard this PR introduces and is derived rather than hardcoded. `azure-pipelines-npm-publish.yml` is deliberately out of scope: it is master-only, its templated comment task already runs with an empty PR number, and it is held harmless by the `continueOnError: true` that `pipeline-pr-comment-steps-guarded.test.ts` enforces. Including it would ship a guard that is red on an unmodified tree, and a guard red on arrival gets deleted rather than obeyed.

## What else is excluded, and why

- **Perf Regression** (~53m) and **Parity Cloud** (~37m) — both BrowserStack. Externally flaky and expensive per run; a post-merge signal from them would be noise rather than information, and would train people to ignore master failures. The lite-gl parity suite still runs post-merge inside Unit Tests, headless on SwiftShader, so the parity harness isn't entirely unwatched.
- **Release Markers** — its entire subject is the pull request (title, body, labels). No PR to inspect on a master build.
- **PR Playground Snapshot** — every variable is derived from the PR number and the point of the job is a PR comment. The master equivalent already exists as `azure-pipelines-playground.yml`.
- **API Report** — ⚠️ **deviation from the original request**, which asked for it as a build-only gate. It carries no unique signal on master:
    - The diff is **empty by construction**. `scripts/report-api-changes.ts` builds its baseline from `git merge-base HEAD origin/master`; on a master build that merge base *is* HEAD. So the report always says "no public API changes", `POST_API_COMMENT` is always false, and the breaking-marker check can never fire — ~2 minutes spent building the package twice (the baseline worktree runs its own `pnpm install`) to assert nothing.
    - The only signal left after removing the diff — "the publishable package builds and its trimmed `index.d.ts` is clean" — is **already covered by Unit Tests**, whose `--project build` suite runs `vite build --mode lib` and `--mode dist` and then type-checks `build/index.d.ts` (`tests/lite/build/public-api-types.test.ts`, `bundler-harness.ts`).

    The reasoning is recorded in a comment on the job so nobody "restores" it later without a reason that survives both points.

## Check names change — verified safe for branch protection

The stage `displayName` no longer says "PR Validation" (it isn't PR-only any more), so the per-job GitHub check contexts change, e.g. `BabylonJS.Babylon-Lite (PR Validation Unit Tests)` becomes `BabylonJS.Babylon-Lite (Validation Unit Tests)`.

That would be a silent merge-blocker if any of those per-job contexts were a *required* status check — a required context that never reports leaves PRs stuck on "Expected — waiting for status to be reported".

Checked before merging: the active **Protect Master** ruleset requires exactly one context, the top-level Azure Pipelines rollup `BabylonJS.Babylon-Lite`, which is the pipeline name and is unaffected by a stage rename. No per-job context is required, and classic branch protection defines no required checks at all. So the rename is safe.

## Required manual follow-up

**ADO notification subscriptions are configured in the ADO UI, not in YAML.** A master failure currently alerts nobody. Someone with project admin needs to add a subscription on *"A build fails"* scoped to this pipeline (Project settings → Notifications). Noted in `TESTING.md` as well.

## Docs

`TESTING.md`'s CI section was stale — it claimed "Five parallel jobs" when there are nine. Refreshed the table with a PR/master column and added a "Post-Merge Validation on `master`" section covering the above.

`GUIDANCE.md` is unchanged: it documents architecture and agent workflow, not the CI job layout, and is immutable without an explicit request.

## Validation

- Every touched YAML parses (`yaml.parse`), and the parsed job list confirms exactly `UnitTests, Lint, Compat` run unconditionally, with all six PR-context jobs gated.
- Verified no `dependsOn` exists anywhere in the file (checked both via the parsed AST and a raw grep), single stage, nine parallel jobs.
- `pnpm lint` exits 0; `prettier --check` clean on both changed files.
- Audited every `System.PullRequest.*` and `GitHubComment@0` reference in the pipeline and in `config/templates/` — all now live in gated jobs. The two templates already have a `postComment` opt-out and are only consumed by PR-only jobs.
- No scene, parity, bundle, or perf suite was run, per the repo guardrails.

### CODE REVIEW

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260805.21 - merge @ 452d53a47844f4aec9b186018cd8505d0fcb3358</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260805.22 - merge @ ce4338d159f4bac9f2e7ece36e729e916fa166f9</sub>

**Comment by bjsplat** [comment]
### Lab - Static Site

[Open deployed site](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260805.21/lab/index.html)

<sub>Build 20260805.21 - merge @ 452d53a47844f4aec9b186018cd8505d0fcb3358</sub>

**Comment by bjsplat** [comment]
### Lab - Static Site

[Open deployed site](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260805.22/lab/index.html)

<sub>Build 20260805.22 - merge @ ce4338d159f4bac9f2e7ece36e729e916fa166f9</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.31 - merge @ 091daefbb80d6a3eaed0eca277dcb0016f624262</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.35 - merge @ c8dd768690e347b34adb401c147d317c4a16ba98</sub>

File: azure-pipelines.yml [hunk 1]
```diff
@@ -1,17 +1,73 @@
...
+# either a no-op or an error. Every such job MUST carry:
+#
+#     condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
+#
+# `Build.SourceBranch` is `refs/pull/<n>/merge` on a PR build and
+# `refs/heads/master` on a master push, so this skips the job exactly when the
+# thing being built *is* master. It is deliberately not `eq(Build.Reason,
+# 'PullRequest')`: that would also skip the job on a manual queue against a
+# feature branch, which is a real workflow (queueing a parity or perf run
+# on-demand) and one this pipeline has always supported.
```
[the remark this answers is not in the document]
Comment (RaananW) [reply azure-pipelines.yml:71]: Fixed ✅ — you're right, and the flaw is in the reasoning rather than the condition.

The paragraph asserted three true things and drew a conclusion that doesn't follow from them: PR context is empty on master → therefore gate on `ne(refs/heads/master)`. But "not master" isn't "is a PR". A build queued by hand against a feature branch is neither, and `System.PullRequest.*` is exactly as empty there as it is on master. So the condition is a *master gate*, and I documented it with a PR-context justification — which teaches the next author that adding it makes PR context safe. It doesn't.

The header now states what the condition does promise, gives the positive form for a job that genuinely can't run without a PR (`startsWith(variables['Build.SourceBranch'], 'refs/pull/')`), and records why no job needs it today.

**I did not change the job conditions**, and the reasoning is worth recording. The gap you identified — manual queue on a feature branch — is a workflow this pipeline deliberately supports (queueing parity or perf on demand), so tightening all six to `refs/pull/` would remove a real capability to fix a problem that's already handled one level down: every PR-context *step* tolerates an absent PR. Verified against the artifact, not assumed — all four `GitHubComment@0` tasks (two here, two in `config/templates/`) are `continueOnError: true` and additionally gated on a `POST_*_COMMENT` flag, and `validate:release-markers` falls back to commit-message scanning when `PR_NUMBER` is empty, treating an unexpanded `$(...)` literal as absent (`cleanAzureValue`, `scripts/validate-pr-release-markers.ts`).

Since that step-level tolerance is now the stated *reason* the weaker gate is acceptable, it's load-bearing prose that a future author acts on — so it's a test rather than a claim: `tests/lite/unit/pipeline-pr-comment-steps-guarded.test.ts`. Verified failing in four directions, including when the collector is broken so it finds nothing.

One residual is named in the comment rather than silently fixed: the Playground Snapshot deploy path (`litePlayground/pr/$(System.PullRequest.PullRequestNumber)`) resolves to a shared `pr/` prefix on a non-PR queue instead of failing loudly. That predates the master trigger, so it's flagged for whoever touches that job rather than changed here.

Job structure confirmed unchanged after the edit: 9 jobs, 6 gated, 3 unconditional.

File: TESTING.md [hunk 2]
```diff
@@ -274,17 +275,59 @@ For local development, add these to `.env.local` (git-ignored).
...
+  enforcement. Duplicating a 42-minute job here is not the fix.)
+- **Release Markers**, **API Report**, and **PR Playground Snapshot** — all
+  inherently PR-scoped. They read `System.PullRequest.PullRequestNumber`, post
+  `GitHubComment@0` comments, or diff against the PR's merge base (which on a
+  master build is the build's own commit, so the diff is empty by construction).
+
+Those jobs are gated with
+`condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')`. **Any new
+job that reads PR context must carry the same condition** — see the header
+comment in `azure-pipelines.yml`.
```
[the remark this answers is not in the document]
Comment (RaananW) [reply TESTING.md]: Fixed ✅ — same correction applied here, since this passage restates the header's rule and inherited the same error.

The section now says plainly that `and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))` is a *master* gate rather than a guarantee that a pull request exists — a manually queued build of a feature branch is neither master nor a PR, and `System.PullRequest.*` is just as empty there — and points at `startsWith(variables['Build.SourceBranch'], 'refs/pull/')` as the form to use for a job that cannot function without a PR at all.

It also now records *why* the weaker gate is survivable, which the previous wording left implicit: every PR-context step tolerates an absent PR (all four `GitHubComment@0` tasks are `continueOnError: true` and gated on a `POST_*_COMMENT` flag; `validate:release-markers` falls back to commit-message scanning). That sentence is now covered by a test rather than left as prose, because it's the stated justification for the gate and a future author will act on it.

Worth noting the docs and the pipeline were checked against each other rather than edited in parallel — this passage already quoted the compound `and(succeeded(), ...)` form matching the YAML, and the job structure is unchanged by the edit (9 jobs, 6 gated, 3 unconditional).

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.65 - merge @ ded17ebece08240eebc7625a49a1a29e71a9bf77</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.72 - merge @ 6ef46a85e1ce21c62c8e5a12064454ea3a5249e4</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.74 - merge @ 14d97c9284d043a7d7eeed9b2dc0280466c3cfab</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.76 - merge @ e87e13b9df9871fdb78bc190037c032479cad1ba</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.78 - merge @ b0c80083f7484a459c29f568890bee21612f9e99</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.80 - merge @ c7e530724336fc5b26ddc9a917ac454a51b8ddad</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.82 - merge @ 159761637fe6293793258e1a89da0098f959d9ba</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.93 - merge @ f94e6d9fd5d0a1b36c912035c1106d0e60559fbd</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.102 - merge @ 61b6e238d34ae068ec003bc2d3d2a56cd69af693</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.116 - merge @ 4d1f1d7f0baa97eff8d864d1d2ac40b7c18a2f8f</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.121 - merge @ d5328b412bcf85a37eb653392f42f583dbb10539</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.123 - merge @ 1cdd6352fc13a1d23f8e2c432aff79cd37639f52</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.131 - merge @ bcb12227db2daca8d93d176504efd995a2ecc014</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.145 - merge @ 9e867868a0d2983b2990f3bb593c98492bb3328c</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.168 - merge @ bc7503bd24e994b85c6ee67792e909d535948cde</sub>

**Comment by bjsplat** [comment]
### Lite Playground - Static Site

[Open deployed site](https://liteplayground.babylonjs.com/pr/531/)

<sub>Build 20260825.183 - merge @ b5ede658c97e36e046a32166fc7ca50fbca7f145</sub>

**Comment by bjsplat** [comment]
### Lab - Static Site

[Open deployed site](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260825.183/lab/index.html)

<sub>Build 20260825.183 - merge @ b5ede658c97e36e046a32166fc7ca50fbca7f145</sub>

**Comment by RaananW** [comment]
Closing this in favour of smaller, separately-reviewable pieces. Nothing is lost — the branch stays, and both halves have a home.

**What this PR contained**, measured against its merge-base (`262250ee`):

| File | Lines |
|---|---|
| `azure-pipelines.yml` | +264/-13 |
| `TESTING.md` | +82/-13 |
| `tests/lite/unit/pipeline-master-gating.test.ts` | +2462 |
| `tests/lite/unit/pipeline-piped-steps-set-pipefail.test.ts` | +1052 |
| `tests/lite/unit/pipeline-files.ts` | +491 |
| `tests/lite/unit/pipeline-pr-comment-steps-guarded.test.ts` | +149 |

That's ~4,150 lines of tests asserting YAML properties against 264 lines of actual pipeline change.

**Where it went:**

- The `set -euo pipefail` fix → **#630**, on its own. This was the load-bearing part and it fixes a live bug: all seven `tsc | sed` type-check steps were reporting green regardless of whether the code type-checked, because a pipeline exits with `sed`'s status and `sed` always exits 0. It needed to ship immediately and without a feature discussion attached.
- Post-merge master validation → **#631**, as an issue.

**The finding in here was real and it was the best catch of the batch** — CI has been asserting "Lint & Type Check ✅" vacuously. Thank you for it. The reason for splitting is not the finding but the packaging: a one-line-per-step correctness fix should not inherit the review cost of a feature plus 4k lines of YAML assertions.

One thing worth noting for #631: post-merge master validation would have been mostly ineffective *before* the pipefail fix, since the master run would have had the identical blind spot. The ordering matters, and this PR had them in one commit range where that dependency was invisible.
