### PR TITLE
fix(build): remove exports for non-existent ssgi & mat4-invert-into modules

### PR DESCRIPTION
**Pull request by georginahalpern**
## Problem

packages/babylon-lite/src/index.ts re-exports three symbols from modules that **do not exist** anywhere in the tree or git history:

- createSsgiPostProcessTask and `type` `SsgiPostProcessTask` / `SsgiPostProcessTaskConfig` from `./post-process/ssgi.js`
- `mat4InvertInto` from `./math/mat4-invert-into.js`

These export lines were introduced in 4c7c3520 (`feat(thin-instance): distance-density thinning in the GPU cull`), but the corresponding source files were never added. As a result the package fails to typecheck/build on `master`:

\\\
src/index.ts: error TS2307: Cannot find module './post-process/ssgi.js' ...
src/index.ts: error TS2307: Cannot find module './math/mat4-invert-into.js' ...
\\\

## Fix

No code anywhere references these symbols (verified across `packages/`, `tests/`, and `lab/`), so the dead exports are simply removed. `pnpm typecheck:lab` passes again.

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

### CODE REVIEW

**Comment by bjsplat** [comment]
### 📋 perf — Test Report

[View full Playwright report](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260611.6/testResults/perf/index.html)

<sub>Build 20260611.6 · merge @ 691e1400d28edd621779c3eb1f0987739a3e9062</sub>

**Comment by bjsplat** [comment]
## Bundle Size Changes

### Increases

| Package | Current | Master | Change |
|---------|---------|--------|--------|
| Scene 224 — Bounding Box Gizmo<br/>`scene224` | 79 KB | 77 KB | **+2 KB** |
| Scene 68 — NME PBR Clearcoat<br/>`scene68` | 91 KB | 90 KB | **+1 KB** |
| Scene 204 - LWR Thin Instances<br/>`scene204` | 50 KB | 49 KB | **+1 KB** |
| Scene 221 — Pointer Drags<br/>`scene221` | 96 KB | 95 KB | **+1 KB** |
| Scene 222 — Composite Gizmos<br/>`scene222` | 105 KB | 104 KB | **+1 KB** |

*Sizes rounded to nearest KB. Run `pnpm build:bundle-scenes` locally to verify.*

**Comment by bjsplat** [comment]
### Lab - Static Site

[Open deployed site](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260611.6/lab/index.html)

<sub>Build 20260611.6 - merge @ 691e1400d28edd621779c3eb1f0987739a3e9062</sub>

**Comment by bjsplat** [comment]
### Lab - Static Site

[Open deployed site](https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/lite/20260611.7/lab/index.html)

<sub>Build 20260611.7 - merge @ e8fc0f7284e86a4a12cbccbbbb21905c2209d5cc</sub>
